package com.work.demo.mapper01;

import com.work.demo.model.FileInfo;
import com.work.demo.model.FileInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    long countByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    int deleteByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    int insertSelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    List<FileInfo> selectByExample(FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") FileInfo record, @Param("example") FileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_INFO
     *
     * @mbg.generated Tue Oct 23 16:48:47 CST 2018
     */
    int updateByExample(@Param("record") FileInfo record, @Param("example") FileInfoExample example);
    
    int deleteAll();
    
    List<FileInfo> queryAll();
}